In [ ]:
import numpy as np

In [ ]:
population = np.random.randint(0, 80, 1000)

In [ ]:
population[0:10]

array([16,  5, 33, 52, 77, 73, 13, 54, 68, 18])

In [ ]:
np.random.seed(115)
example = np.random.choice(a=population, size=100)
example[0:100]

array([24, 61, 33, 68,  9, 15, 62, 32, 31,  1,  9, 70,  2, 77, 48, 14, 26,
       54, 57, 63, 11,  1, 20, 28, 26, 11, 56, 17, 36, 70, 78, 70,  2, 53,
       19, 17, 31, 14, 38, 11, 61, 37, 20, 51, 23, 44, 46, 58, 15, 31, 61,
       74, 21, 37,  9,  4, 24,  3, 71, 61, 68,  0, 19, 18, 45, 42,  9, 31,
       13, 57, 24, 73, 75, 16, 21, 50, 71, 68, 74,  2, 23, 77, 17,  2, 36,
       30,  9, 16, 53, 63, 70,  8, 13, 60, 68, 23, 11, 53, 21, 71])

In [ ]:
example.mean()

36.16

In [ ]:
population.mean()

37.577

In [ ]:
np.random.seed(10)
example1 = np.random.choice(a=population, size=100)
example2 = np.random.choice(a=population, size=100)
example3 = np.random.choice(a=population, size=100)
example4 = np.random.choice(a=population, size=100)
example5 = np.random.choice(a=population, size=100)
example6 = np.random.choice(a=population, size=100)
example7 = np.random.choice(a=population, size=100)
example8 = np.random.choice(a=population, size=100)
example9 = np.random.choice(a=population, size=100)
example10 = np.random.choice(a=population, size=100)

In [ ]:
example_total = (example1.mean() +  example2.mean() + example3.mean() + example4.mean() + example5.mean() +
 example6.mean() + example7.mean() + example8.mean() + example8.mean() + example9.mean() + example10.mean() )
example_total

422.36999999999995

In [ ]:
import seaborn as sns
tips = sns.load_dataset('tips')
df = tips.copy()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [ ]:
!pip install researchpy
import researchpy as rp

Collecting researchpy
  Downloading researchpy-0.3.6-py3-none-any.whl (34 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from researchpy) (1.11.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from researchpy) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from researchpy) (2.0.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from researchpy) (0.14.2)
Requirement already satisfied: patsy in /usr/local/lib/python3.10/dist-packages (from researchpy) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->researchpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->researchpy) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->researchpy) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy->researchpy) (1.16.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels->researchpy) (24.1)
Installing collected packages: researchpy
Successfully installed researchpy-0.3.6

In [ ]:
rp.summary_cont(df[['total_bill', 'tip', 'size']])

     Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [ ]:
rp.summary_cat(df[['sex', 'smoker', 'day']]).T

              0       1       2      3      4      5      6     7
Variable    sex          smoker           day
Outcome    Male  Female      No    Yes    Sat    Sun   Thur   Fri
Count       157      87     151     93     87     76     62    19
Percent   64.34   35.66   61.89  38.11  35.66  31.15  25.41  7.79

In [ ]:
df[['tip', 'total_bill']].cov()

                 tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [ ]:
df[['tip', 'total_bill']].corr()

                 tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000